default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch('APP_DATABASE_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('APP_DATABASE_PASSWORD') { 'postgres' } %>
  host: <%= ENV.fetch('APP_DATABASE_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('APP_DATABASE_PORT') { 5432 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: desafio_ninja_development

test:
  <<: *default
  database: desafio_ninja_test

production:
  <<: *default
  database: desafio_ninja_production
  username: desafio_ninja
  password: <%= ENV['DESAFIO_NINJA_DATABASE_PASSWORD'] %>
